### ISSUE TITLE
Add player tags for alignment and classes

### ISSUE THREAD

**Issue by legoraft** [ominouspink/mc-sWrath#5]
For the questline we're going to use questlines depending on player alignment and player class. There have to be some tags registered on the player for this to work.

These tags also need to be implemented into the advancement api to make the quests working.

### Todo
- [ ] Add custom tags, events or statistics to player for datapack integration.
- [ ] Add quests for storyline, alignment and class
- [ ] Add custom textures/items or backgrounds to make the quest tree as good as possible
